pipeline{
    agent any

    Parameters{
        string(name: 'ENV',defaultValue: 'Prod',description: 'Environment to deploy')
    }
    
    stages{
        stage('build'){
            steps{
                echo "Deploying to ${params.ENV} environment"
            }
        }
    }
}