pipeline{
    
    agent any

    stages{
        stage(basic){
            steps{
                sh '''
                echo "Hello good morning..."
                '''
            }
        }        
    }
}