pipeline{
    agent {
        label 'test'
    }
    stages{
        stage('checkout'){
            steps {
                git url : 'https://github.com/muniraj-git/Git-Test1.git' , branch: 'main'
            }
        }
    }
}